### ISSUE TITLE
Expression is not allowed as field default value

### ISSUE THREAD

**Issue by cristiancalara** [brendo/emailtemplate#1]
I am receiving a syntax error for private $templatePath = **DIR** . '/../../templates'; in EmailTemplate\Message\EmailTemplate class because expression is not allowed as field default value.

This happens with php version 5.4.39.

I don`t think this is a big issue, but just wanted to let you know.

**Comment by brendo** [comment]
Ah! Thanks @cristiancalara. Without even realising it that variable is using on the new [PHP 5.6](http://php.net/manual/en/migration56.new-features.php) features that allow expressions. I'll tidy this up so the library has better compatibility with older PHP versions.
